version: '3.7'

services:
  postgres:
    container_name: pucrs-microservice-payment-nest-pg
    image: bitnami/postgresql:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=microservice-payment-nest-pg